
DROP TABLE IF EXISTS CRYPTO_CURRENCY;
 
CREATE TABLE CRYPTO_CURRENCY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) 
 
);



DROP TABLE IF EXISTS CRYPTO_CURRENCY_TRADE_DETAILS;
 
CREATE TABLE CRYPTO_CURRENCY_TRADE_DETAILS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TRADE_DATE Date ,
  TRADE_TIME VARCHAR(250) ,
  PRICE DECIMAL,
  CURRENCY_ID INT,
   foreign key (CURRENCY_ID) references CRYPTO_CURRENCY(ID)
);